// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIL6focpasgCMdzbn8yhKrg99xIg8_79U',
    appId: '1:982257734467:web:56ab17ac29e2bf7b1c95f6',
    messagingSenderId: '982257734467',
    projectId: 'tugasbesarapb',
    authDomain: 'tugasbesarapb.firebaseapp.com',
    storageBucket: 'tugasbesarapb.firebasestorage.app',
    measurementId: 'G-1B068JV2FW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXVkOBYH4rzJHVLXssZrLgaFQiTEEa1ag',
    appId: '1:982257734467:android:56c3d520f3a6f4de1c95f6',
    messagingSenderId: '982257734467',
    projectId: 'tugasbesarapb',
    storageBucket: 'tugasbesarapb.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhlgdDwOKLELJ7OxJmJ6iKjlChA-IprLA',
    appId: '1:982257734467:ios:995836bf267ce3e91c95f6',
    messagingSenderId: '982257734467',
    projectId: 'tugasbesarapb',
    storageBucket: 'tugasbesarapb.firebasestorage.app',
    iosBundleId: 'com.bustedworld.bustedworld',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhlgdDwOKLELJ7OxJmJ6iKjlChA-IprLA',
    appId: '1:982257734467:ios:995836bf267ce3e91c95f6',
    messagingSenderId: '982257734467',
    projectId: 'tugasbesarapb',
    storageBucket: 'tugasbesarapb.firebasestorage.app',
    iosBundleId: 'com.bustedworld.bustedworld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIL6focpasgCMdzbn8yhKrg99xIg8_79U',
    appId: '1:982257734467:web:451c95c03a2f0dff1c95f6',
    messagingSenderId: '982257734467',
    projectId: 'tugasbesarapb',
    authDomain: 'tugasbesarapb.firebaseapp.com',
    storageBucket: 'tugasbesarapb.firebasestorage.app',
    measurementId: 'G-Z2WQVSMKF4',
  );
}
